apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
  namespace: apps
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      serviceAccountName: app1-sa
      automountServiceAccountToken: false
      containers:
        - name: api
          image: alpine:3.14
          command:
            - "/bin/sh"
            - "/script/run.sh"
          envFrom:
            - configMapRef:
                name: app1-configmap
          volumeMounts:
            - name: script
              mountPath: /script
          resources:
            requests:
              memory: {{ .Values.api_resources.requests.memory }}
              cpu: {{ .Values.api_resources.requests.cpu }}
            limits:
              memory: {{ .Values.api_resources.limits.memory }}
              cpu: {{ .Values.api_resources.limits.cpu }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
      volumes:
        - name: script
          configMap:
            name: script-configmap
