apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
  namespace: apps
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-sa
      automountServiceAccountToken: false
      containers:
        - name: api
          image: {{ .Values.application.api.image }}
          command:
            - "/bin/sh"
            - "/script/run.sh"
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
          volumeMounts:
            - name: script
              mountPath: /script
          resources:
            requests:
              memory: {{ .Values.application.api.resources.requests.memory }}
              cpu: {{ .Values.application.api.resources.requests.cpu }}
            limits:
              memory: {{ .Values.application.api.resources.limits.memory }}
              cpu: {{ .Values.application.api.resources.limits.cpu }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
      volumes:
        - name: script
          configMap:
            name: script-configmap
